language: python
python:
  - '3.6'
install:
  - pip install --upgrade setuptools
  - python setup.py install
  - pip install -r requirements.txt
  - python -c "import sys; print(sys.path)"
before_install:
  - chmod +x ./.travis/build.sh
script:
  - ./.travis/run.sh  
branches:
  only:
    - master
    - dev
